#include "hdl_export.hpp"

#include <algorithm>
#include <cctype>
#include <cmath>
#include <limits>
#include <map>
#include <sstream>
#include <tuple>

namespace pyfda {

std::string export_coe(const Vec &b, const QFormat &qcb, int radix) {
    const Vec bq = quant_coeffs(b, qcb);
    std::ostringstream o;
    o << "; Xilinx COE file exported by pyfda_cpp\n; " << bq.size() << " coefficients, Q" << qcb.WI << "." << qcb.WF
      << " (" << qcb.W() << " bit, two's complement)\n";
    o << "Radix = " << radix << ";\nCoefData =\n";
    for (size_t i = 0; i < bq.size(); ++i) {
        const long long v = to_int(bq[i], qcb);
        o << (radix == 16 ? to_base(v, qcb.W(), 16) : std::to_string(v)) << (i + 1 < bq.size() ? ",\n" : ";\n");
    }
    return o.str();
}

std::string vhdl_identifier(const std::string &name) {
    std::string id;
    for (char c : name) {
        const bool ok = std::isalnum(static_cast<unsigned char>(c)) != 0;
        if (ok) id += char(std::tolower(static_cast<unsigned char>(c)));
        else if (!id.empty() && id.back() != '_') id += '_';
    }
    while (!id.empty() && id.back() == '_') id.pop_back();
    if (id.empty() || !std::isalpha(static_cast<unsigned char>(id[0]))) id = "f_" + id;
    return id;
}

namespace {

int quant_code(Quant q) {
    switch (q) {
    case Quant::Floor: return 0;
    case Quant::Round: return 1;
    case Quant::Fix: return 2;
    case Quant::Ceil: return 3;
    case Quant::None: break;
    }
    throw DesignError("Quantization 'none' can't be implemented in hardware, use floor, round, fix or ceil.");
}

std::string sat(const QFormat &q) { return q.ovfl == Ovfl::Sat ? "true" : "false"; }

int clog2(size_t n) {
    int b = 0;
    while ((size_t(1) << b) < n) ++b;
    return b;
}

void check_width(const QFormat &q, const char *name) {
    if (q.W() < 2 || q.W() > 64) throw DesignError(std::string("The word length of ") + name + " must be 2 ... 64 bits.");
}

// requantization function (VHDL-2008): v has `wf_in` fractional bits, the result has
// `wf_out` fractional bits and `w_out` bits; quantization like numpy floor / round
// (half to even) / trunc / ceil, overflow by saturation or two's complement wrap
const char *REQUANT_FUNC = R"(    -- requantize v with wf_in fractional bits to w_out bits with wf_out fractional bits
    -- q: 0 = floor, 1 = round (half to even), 2 = fix (towards zero), 3 = ceil
    function requant(v : signed; wf_in, wf_out, w_out, q : integer; sat : boolean) return signed is
        constant s : integer := wf_in - wf_out;
        constant wt : integer := maximum(v'length, s + 1) + 2;
        constant we : integer := maximum(wt, v'length + maximum(-s, 0) + 1);
        variable t : signed(wt - 1 downto 0);
        variable e : signed(we - 1 downto 0);
        variable one : signed(we - 1 downto 0);
        variable keep_lsb : std_logic;
    begin
        if s > 0 then
            t := resize(v, wt);
            if q = 1 then
                -- add half an LSB - 1 plus the LSB of the kept part (round half to even)
                if s < v'length then
                    keep_lsb := v(v'low + s);
                else
                    keep_lsb := v(v'high);
                end if;
                t := t + shift_left(to_signed(1, wt), s - 1) - 1;
                if keep_lsb = '1' then
                    t := t + 1;
                end if;
            elsif q = 3 or (q = 2 and v(v'high) = '1') then
                t := t + shift_left(to_signed(1, wt), s) - 1;
            end if;
            e := resize(shift_right(t, s), we);
        else
            e := shift_left(resize(v, we), -s);
        end if;
        if we > w_out then
            if sat then
                one := to_signed(1, we);
                if e > shift_left(one, w_out - 1) - 1 then
                    e := shift_left(one, w_out - 1) - 1;
                elsif e < -shift_left(one, w_out - 1) then
                    e := -shift_left(one, w_out - 1);
                end if;
            end if;
            return e(w_out - 1 downto 0);  -- saturated or two's complement wrap around
        end if;
        return resize(e, w_out);
    end function;
)";

std::string header(const std::string &what, const FxSpec &s, bool iir) {
    std::ostringstream o;
    auto fmt = [](const QFormat &q) {
        std::ostringstream f;
        f << "Q" << q.WI << "." << q.WF << " (" << q.W() << " bit, " << quant_key(q.quant) << ", " << ovfl_key(q.ovfl) << ")";
        return f.str();
    };
    o << "-- " << what << ", generated by pyfda_cpp\n--\n";
    o << "-- input x:        " << fmt(s.qi) << "\n";
    o << "-- coefficients b: " << fmt(s.qcb) << "\n";
    if (iir) o << "-- coefficients a: " << fmt(s.qca) << "\n";
    o << "-- accumulator:    " << fmt(s.qacc) << "\n";
    o << "-- output y:       " << fmt(s.qo) << "\n--\n";
    o << "-- y is registered: the output for the sample x applied with en = '1' is\n"
         "-- available after the next rising clock edge.\n\n";
    o << "library ieee;\nuse ieee.std_logic_1164.all;\nuse ieee.numeric_std.all;\n\n";
    return o.str();
}

std::string entity(const std::string &name, const FxSpec &s) {
    std::ostringstream o;
    o << "entity " << name << " is\n    port (\n        clk : in  std_logic;\n        rst : in  std_logic;\n"
      << "        en  : in  std_logic;\n        x   : in  signed(" << s.qi.W() - 1 << " downto 0);\n"
      << "        y   : out signed(" << s.qo.W() - 1 << " downto 0)\n    );\nend entity;\n\n";
    return o.str();
}

std::string coeff_list(const Vec &c, const QFormat &q, int indent) {
    std::ostringstream o;
    for (size_t i = 0; i < c.size(); ++i) {
        if (i % 4 == 0) o << (i ? ",\n" : "") << std::string(size_t(indent), ' ');
        else o << ", ";
        o << "to_signed(" << to_int(c[i], q) << ", " << q.W() << ")";
    }
    return o.str();
}

}  // namespace

std::string export_vhdl_fir(const Vec &b, const FxSpec &s, const std::string &name_in) {
    for (auto [q, n] : {std::pair{&s.qi, "the input"}, {&s.qcb, "the coefficients"}, {&s.qacc, "the accumulator"},
                        {&s.qo, "the output"}})
        check_width(*q, n);
    quant_code(s.qacc.quant);
    quant_code(s.qo.quant);
    if (b.empty()) throw DesignError("No coefficients.");
    const std::string name = vhdl_identifier(name_in);
    const Vec bq = quant_coeffs(b, s.qcb);
    const size_t L = bq.size();
    const int w_prod = s.qi.W() + s.qcb.W();
    const int w_sum = s.qacc.W() + clog2(L) + 1;
    std::ostringstream o;
    o << header("FIR filter in direct form, " + std::to_string(L) + " taps", s, false) << entity(name, s);
    o << "architecture rtl of " << name << " is\n";
    o << "    constant L : integer := " << L << ";\n";
    o << "    type coeff_t is array (0 to L - 1) of signed(" << s.qcb.W() - 1 << " downto 0);\n";
    o << "    constant B : coeff_t := (\n" << coeff_list(bq, s.qcb, 8) << (L == 1 ? ", others => (others => '0')" : "")
      << ");\n";
    o << "    type taps_t is array (0 to L - 1) of signed(" << s.qi.W() - 1 << " downto 0);\n";
    o << "    signal taps : taps_t := (others => (others => '0'));\n\n" << REQUANT_FUNC << "begin\n";
    o << "    process (clk)\n        variable t : taps_t;\n        variable p : signed(" << w_prod - 1 << " downto 0);\n"
      << "        variable acc : signed(" << w_sum - 1 << " downto 0);\n    begin\n"
      << "        if rising_edge(clk) then\n            if rst = '1' then\n"
      << "                taps <= (others => (others => '0'));\n                y <= (others => '0');\n"
      << "            elsif en = '1' then\n"
      << "                t(0) := x;\n                for i in 1 to L - 1 loop\n                    t(i) := taps(i - 1);\n"
      << "                end loop;\n                acc := (others => '0');\n                for i in 0 to L - 1 loop\n"
      << "                    p := t(i) * B(i);\n"
      << "                    acc := acc + resize(requant(p, " << s.qi.WF + s.qcb.WF << ", " << s.qacc.WF << ", "
      << s.qacc.W() << ", " << quant_code(s.qacc.quant) << ", " << sat(s.qacc) << "), acc'length);\n"
      << "                end loop;\n"
      << "                y <= requant(requant(acc, " << s.qacc.WF << ", " << s.qacc.WF << ", " << s.qacc.W() << ", 0, "
      << sat(s.qacc) << "), " << s.qacc.WF << ", " << s.qo.WF << ", " << s.qo.W() << ", " << quant_code(s.qo.quant)
      << ", " << sat(s.qo) << ");\n"
      << "                taps <= t;\n            end if;\n        end if;\n    end process;\nend architecture;\n";
    return o.str();
}

std::string export_vhdl_sos(const Sos &sos, const FxSpec &s, const std::string &name_in) {
    for (auto [q, n] : {std::pair{&s.qi, "the input"}, {&s.qcb, "the b coefficients"}, {&s.qca, "the a coefficients"},
                        {&s.qacc, "the accumulator"}, {&s.qo, "the output"}})
        check_width(*q, n);
    quant_code(s.qacc.quant);
    quant_code(s.qo.quant);
    if (sos.empty()) throw DesignError("No second-order sections.");
    const std::string name = vhdl_identifier(name_in);
    Vec b, a;
    for (const auto &sec : sos) {
        if (sec[3] != 1.0) throw DesignError("Second-order sections must be normalized to a0 = 1.");
        b.insert(b.end(), {sec[0], sec[1], sec[2]});
        a.insert(a.end(), {sec[4], sec[5]});
    }
    const Vec bq = quant_coeffs(b, s.qcb), aq = quant_coeffs(a, s.qca);
    const size_t n = sos.size();
    // the section inputs are the filter input (section 0) or the outputs of the previous section,
    // registers are kept in a common format with WF_s fractional and W_s bits
    const int wf_s = std::max(s.qi.WF, s.qo.WF);
    const int wi_s = std::max(s.qi.WI, s.qo.WI);
    const int w_s = wi_s + wf_s + 1;
    const int w_sum = s.qacc.W() + 4;
    std::ostringstream o;
    o << header("IIR filter, cascade of " + std::to_string(n) + " second-order sections in direct form 1", s, true)
      << entity(name, s);
    o << "architecture rtl of " << name << " is\n";
    o << "    constant NS : integer := " << n << ";\n";
    o << "    type b_t is array (0 to 3 * NS - 1) of signed(" << s.qcb.W() - 1 << " downto 0);\n";
    o << "    type a_t is array (0 to 2 * NS - 1) of signed(" << s.qca.W() - 1 << " downto 0);\n";
    o << "    -- b0, b1, b2 of every section\n    constant B : b_t := (\n" << coeff_list(bq, s.qcb, 8) << ");\n";
    o << "    -- a1, a2 of every section (a0 = 1)\n    constant A : a_t := (\n" << coeff_list(aq, s.qca, 8) << ");\n";
    o << "    -- section inputs and outputs with " << wf_s << " fractional bits\n";
    o << "    type reg_t is array (0 to NS - 1) of signed(" << w_s - 1 << " downto 0);\n";
    o << "    signal x1, x2, y1, y2 : reg_t := (others => (others => '0'));\n\n" << REQUANT_FUNC << "begin\n";
    o << "    process (clk)\n        variable xs, ys : signed(" << w_s - 1 << " downto 0);\n"
      << "        variable yo : signed(" << s.qo.W() - 1 << " downto 0);\n"
      << "        variable acc_b, acc_a : signed(" << w_sum - 1 << " downto 0);\n"
      << "        variable acc : signed(" << s.qacc.W() - 1 << " downto 0);\n    begin\n"
      << "        if rising_edge(clk) then\n            if rst = '1' then\n"
      << "                x1 <= (others => (others => '0'));\n                x2 <= (others => (others => '0'));\n"
      << "                y1 <= (others => (others => '0'));\n                y2 <= (others => (others => '0'));\n"
      << "                y <= (others => '0');\n            elsif en = '1' then\n"
      << "                xs := shift_left(resize(x, xs'length), " << wf_s - s.qi.WF << ");\n"
      << "                for k in 0 to NS - 1 loop\n";
    auto prod_b = [&](const std::string &c, const std::string &v) {
        return "resize(requant(" + v + " * " + c + ", " + std::to_string(wf_s + s.qcb.WF) + ", " +
               std::to_string(s.qacc.WF) + ", " + std::to_string(s.qacc.W()) + ", " +
               std::to_string(quant_code(s.qacc.quant)) + ", " + sat(s.qacc) + "), acc_b'length)";
    };
    auto prod_a = [&](const std::string &c, const std::string &v) {
        return "resize(requant(" + v + " * " + c + ", " + std::to_string(wf_s + s.qca.WF) + ", " +
               std::to_string(s.qacc.WF) + ", " + std::to_string(s.qacc.W()) + ", " +
               std::to_string(quant_code(s.qacc.quant)) + ", " + sat(s.qacc) + "), acc_a'length)";
    };
    o << "                    acc_b := " << prod_b("B(3 * k)", "xs") << "\n                           + "
      << prod_b("B(3 * k + 1)", "x1(k)") << "\n                           + " << prod_b("B(3 * k + 2)", "x2(k)")
      << ";\n";
    o << "                    acc_a := " << prod_a("A(2 * k)", "y1(k)") << "\n                           + "
      << prod_a("A(2 * k + 1)", "y2(k)") << ";\n";
    o << "                    acc := requant(acc_b - acc_a, " << s.qacc.WF << ", " << s.qacc.WF << ", " << s.qacc.W()
      << ", 0, " << sat(s.qacc) << ");\n";
    o << "                    yo := requant(acc, " << s.qacc.WF << ", " << s.qo.WF << ", " << s.qo.W() << ", "
      << quant_code(s.qo.quant) << ", " << sat(s.qo) << ");\n";
    o << "                    ys := shift_left(resize(yo, ys'length), " << wf_s - s.qo.WF << ");\n";
    o << "                    x2(k) <= x1(k);\n                    x1(k) <= xs;\n"
      << "                    y2(k) <= y1(k);\n                    y1(k) <= ys;\n"
      << "                    xs := ys;  -- input of the next section\n                end loop;\n"
      << "                y <= yo;\n            end if;\n        end if;\n    end process;\nend architecture;\n";
    return o.str();
}

// ---------------------------------------------------------------------------
// Verilog
// ---------------------------------------------------------------------------
namespace {

std::string vlit(long long v, int w) {
    // sized signed literal, e.g. -16'sd123; the most negative value can't be written
    // as -16'sd32768 (the negation overflows after sign extension)
    if (w <= 64 && v < 0 && (w == 64 ? v == std::numeric_limits<long long>::min() : v == -(1LL << (w - 1))))
        return "$signed({1'b1, {" + std::to_string(w - 1) + "{1'b0}}})";
    const unsigned long long m = v < 0 ? 0ULL - static_cast<unsigned long long>(v) : static_cast<unsigned long long>(v);
    return (v < 0 ? "-" : "") + std::to_string(w) + "'sd" + std::to_string(m);
}

std::string vpow2(int e, int w, long long add = 0) {
    // (2^e + add) as sized signed literal with w bits, e <= 63
    const unsigned long long p = (e >= 64 ? 0ULL : (1ULL << e));
    const unsigned long long v = add >= 0 ? p + static_cast<unsigned long long>(add) : p - static_cast<unsigned long long>(-add);
    return std::to_string(w) + "'sd" + std::to_string(v);
}

// Requantization functions with fixed widths, generated on demand (same arithmetic
// as the VHDL function requant)
class VRequant {
public:
    std::string call(const std::string &arg, int w_in, int wf_in, int wf_out, int w_out, Quant q, bool sat) {
        const auto key = std::make_tuple(w_in, wf_in, wf_out, w_out, quant_code(q), sat);
        auto it = m_names.find(key);
        if (it == m_names.end()) {
            const std::string name = "rq" + std::to_string(m_names.size());
            it = m_names.emplace(key, name).first;
            m_code += define(name, w_in, wf_in, wf_out, w_out, quant_code(q), sat);
        }
        return it->second + "(" + arg + ")";
    }
    const std::string &code() const { return m_code; }

private:
    static std::string define(const std::string &name, int w_in, int wf_in, int wf_out, int w_out, int q, bool sat) {
        const int s = wf_in - wf_out;
        const int wt = std::max(w_in, s + 1) + 2;
        const int we = std::max(wt, w_in + std::max(-s, 0) + 1);
        if (s > 62) throw DesignError("Too many fractional bits to discard for Verilog export.");
        std::ostringstream o;
        o << "    // requantize " << w_in << " bit (" << wf_in << " frac.) -> " << w_out << " bit (" << wf_out
          << " frac.), " << (q == 0 ? "floor" : q == 1 ? "round" : q == 2 ? "fix" : "ceil") << ", "
          << (sat ? "sat" : "wrap") << "\n";
        o << "    function signed [" << w_out - 1 << ":0] " << name << ";\n";
        o << "        input signed [" << w_in - 1 << ":0] v;\n";
        o << "        reg signed [" << wt - 1 << ":0] t;\n        reg signed [" << we - 1 << ":0] e;\n";
        o << "        begin\n";
        if (s > 0) {
            o << "            t = v;\n";
            if (q == 1) {
                const std::string keep = s < w_in ? "v[" + std::to_string(s) + "]" : "v[" + std::to_string(w_in - 1) + "]";
                o << "            t = t + " << vpow2(s - 1, wt, -1) << " + {{" << wt - 1 << "{1'b0}}, " << keep << "};\n";
            } else if (q == 3) {
                o << "            t = t + " << vpow2(s, wt, -1) << ";\n";
            } else if (q == 2) {
                o << "            if (v[" << w_in - 1 << "]) t = t + " << vpow2(s, wt, -1) << ";\n";
            }
            o << "            e = t >>> " << s << ";\n";
        } else {
            o << "            e = v;\n";
            if (s < 0) o << "            e = e <<< " << -s << ";\n";
        }
        if (we > w_out && sat) {
            o << "            if (e > " << vpow2(w_out - 1, we, -1) << ") e = " << vpow2(w_out - 1, we, -1) << ";\n";
            o << "            else if (e < -" << vpow2(w_out - 1, we) << ") e = -" << vpow2(w_out - 1, we) << ";\n";
        }
        o << "            " << name << " = e;  // keeps the LSBs (wrap around) or sign extends\n";
        o << "        end\n    endfunction\n\n";
        return o.str();
    }
    std::map<std::tuple<int, int, int, int, int, bool>, std::string> m_names;
    std::string m_code;
};

std::string vheader(const std::string &what, const FxSpec &s, bool iir) {
    std::string h = header(what, s, iir);
    // VHDL comments -> Verilog comments, drop the library clauses
    std::string out;
    std::istringstream in(h);
    std::string line;
    while (std::getline(in, line)) {
        if (line.rfind("library", 0) == 0 || line.rfind("use ", 0) == 0) continue;
        if (line.rfind("--", 0) == 0) line = "//" + line.substr(2);
        out += line + "\n";
    }
    while (out.size() > 1 && out[out.size() - 1] == '\n' && out[out.size() - 2] == '\n') out.pop_back();
    return out + "\n";
}

std::string vports(const std::string &name, const FxSpec &s) {
    std::ostringstream o;
    o << "module " << name << " (\n    input  wire clk,\n    input  wire rst,\n    input  wire en,\n"
      << "    input  wire signed [" << s.qi.W() - 1 << ":0] x,\n"
      << "    output reg  signed [" << s.qo.W() - 1 << ":0] y\n);\n\n";
    return o.str();
}

}  // namespace

std::string export_verilog_fir(const Vec &b, const FxSpec &s, const std::string &name_in) {
    for (auto [q, n] : {std::pair{&s.qi, "the input"}, {&s.qcb, "the coefficients"}, {&s.qacc, "the accumulator"},
                        {&s.qo, "the output"}})
        check_width(*q, n);
    quant_code(s.qacc.quant);
    quant_code(s.qo.quant);
    if (b.empty()) throw DesignError("No coefficients.");
    const std::string name = vhdl_identifier(name_in);
    const Vec bq = quant_coeffs(b, s.qcb);
    const size_t L = bq.size();
    const int w_prod = s.qi.W() + s.qcb.W();
    const int w_sum = s.qacc.W() + clog2(L) + 1;
    VRequant rq;
    std::ostringstream body;
    body << "    always @(posedge clk) begin\n        if (rst) begin\n";
    for (size_t i = 1; i < L; ++i) body << "            t" << i << " <= 0;\n";
    body << "            y <= 0;\n        end else if (en) begin\n            acc = 0;\n";
    for (size_t i = 0; i < L; ++i) {
        body << "            p = " << (i == 0 ? std::string("x") : "t" + std::to_string(i)) << " * "
             << vlit(to_int(bq[i], s.qcb), s.qcb.W()) << ";\n";
        body << "            acc = acc + "
             << rq.call("p", w_prod, s.qi.WF + s.qcb.WF, s.qacc.WF, s.qacc.W(), s.qacc.quant, s.qacc.ovfl == Ovfl::Sat)
             << ";\n";
    }
    const std::string acc_q =
        rq.call("acc", w_sum, s.qacc.WF, s.qacc.WF, s.qacc.W(), Quant::Floor, s.qacc.ovfl == Ovfl::Sat);
    body << "            accq = " << acc_q << ";\n";
    body << "            y <= " << rq.call("accq", s.qacc.W(), s.qacc.WF, s.qo.WF, s.qo.W(), s.qo.quant, s.qo.ovfl == Ovfl::Sat)
         << ";\n";
    for (size_t i = L - 1; i >= 1; --i)
        body << "            t" << i << " <= " << (i == 1 ? std::string("x") : "t" + std::to_string(i - 1)) << ";\n";
    body << "        end\n    end\n\nendmodule\n";

    std::ostringstream o;
    o << vheader("FIR filter in direct form, " + std::to_string(L) + " taps", s, false) << vports(name, s);
    o << "    // delay line x[n-1] ... x[n-" << L - 1 << "]\n";
    for (size_t i = 1; i < L; ++i) o << "    reg signed [" << s.qi.W() - 1 << ":0] t" << i << " = 0;\n";
    o << "    reg signed [" << w_prod - 1 << ":0] p;\n    reg signed [" << w_sum - 1 << ":0] acc;\n"
      << "    reg signed [" << s.qacc.W() - 1 << ":0] accq;\n\n";
    o << rq.code() << body.str();
    return o.str();
}

std::string export_verilog_sos(const Sos &sos, const FxSpec &s, const std::string &name_in) {
    for (auto [q, n] : {std::pair{&s.qi, "the input"}, {&s.qcb, "the b coefficients"}, {&s.qca, "the a coefficients"},
                        {&s.qacc, "the accumulator"}, {&s.qo, "the output"}})
        check_width(*q, n);
    quant_code(s.qacc.quant);
    quant_code(s.qo.quant);
    if (sos.empty()) throw DesignError("No second-order sections.");
    const std::string name = vhdl_identifier(name_in);
    const int wf_s = std::max(s.qi.WF, s.qo.WF);
    const int wi_s = std::max(s.qi.WI, s.qo.WI);
    const int w_s = wi_s + wf_s + 1;
    const int w_sum = s.qacc.W() + 4;
    const int w_pb = w_s + s.qcb.W(), w_pa = w_s + s.qca.W();
    const bool sat_acc = s.qacc.ovfl == Ovfl::Sat;
    VRequant rq;
    std::ostringstream body;
    const size_t n = sos.size();
    body << "    always @(posedge clk) begin\n        if (rst) begin\n";
    for (size_t k = 0; k < n; ++k)
        body << "            x1_" << k << " <= 0; x2_" << k << " <= 0; y1_" << k << " <= 0; y2_" << k << " <= 0;\n";
    body << "            y <= 0;\n        end else if (en) begin\n";
    body << "            xs = x;\n";
    if (wf_s - s.qi.WF > 0) body << "            xs = xs <<< " << wf_s - s.qi.WF << ";\n";
    for (size_t k = 0; k < n; ++k) {
        const auto &sec = sos[k];
        if (sec[3] != 1.0) throw DesignError("Second-order sections must be normalized to a0 = 1.");
        const Vec bq = quant_coeffs({sec[0], sec[1], sec[2]}, s.qcb), aq = quant_coeffs({sec[4], sec[5]}, s.qca);
        const std::string K = std::to_string(k);
        auto pb = [&](const std::string &v, double c) {
            body << "            pb = " << v << " * " << vlit(to_int(c, s.qcb), s.qcb.W()) << ";\n";
            return rq.call("pb", w_pb, wf_s + s.qcb.WF, s.qacc.WF, s.qacc.W(), s.qacc.quant, sat_acc);
        };
        auto pa = [&](const std::string &v, double c) {
            body << "            pa = " << v << " * " << vlit(to_int(c, s.qca), s.qca.W()) << ";\n";
            return rq.call("pa", w_pa, wf_s + s.qca.WF, s.qacc.WF, s.qacc.W(), s.qacc.quant, sat_acc);
        };
        body << "            // section " << k << "\n";
        // pb / pa write the product into the body and return the requantization call
        std::string r = pb("xs", bq[0]);
        body << "            acc_b = " << r << ";\n";
        r = pb("x1_" + K, bq[1]);
        body << "            acc_b = acc_b + " << r << ";\n";
        r = pb("x2_" + K, bq[2]);
        body << "            acc_b = acc_b + " << r << ";\n";
        r = pa("y1_" + K, aq[0]);
        body << "            acc_a = " << r << ";\n";
        r = pa("y2_" + K, aq[1]);
        body << "            acc_a = acc_a + " << r << ";\n";
        body << "            acc = acc_b - acc_a;\n";
        body << "            accq = " << rq.call("acc", w_sum, s.qacc.WF, s.qacc.WF, s.qacc.W(), Quant::Floor, sat_acc) << ";\n";
        body << "            yo = " << rq.call("accq", s.qacc.W(), s.qacc.WF, s.qo.WF, s.qo.W(), s.qo.quant, s.qo.ovfl == Ovfl::Sat)
             << ";\n";
        body << "            ys = yo;\n";
        if (wf_s - s.qo.WF > 0) body << "            ys = ys <<< " << wf_s - s.qo.WF << ";\n";
        body << "            x2_" << K << " <= x1_" << K << "; x1_" << K << " <= xs; y2_" << K << " <= y1_" << K << "; y1_"
             << K << " <= ys;\n";
        body << "            xs = ys;\n";
    }
    body << "            y <= yo;\n        end\n    end\n\nendmodule\n";

    std::ostringstream o;
    o << vheader("IIR filter, cascade of " + std::to_string(n) + " second-order sections in direct form 1", s, true)
      << vports(name, s);
    o << "    // section inputs and outputs with " << wf_s << " fractional bits\n";
    for (size_t k = 0; k < n; ++k)
        o << "    reg signed [" << w_s - 1 << ":0] x1_" << k << " = 0, x2_" << k << " = 0, y1_" << k << " = 0, y2_" << k
          << " = 0;\n";
    o << "    reg signed [" << w_s - 1 << ":0] xs, ys;\n    reg signed [" << s.qo.W() - 1 << ":0] yo;\n"
      << "    reg signed [" << w_pb - 1 << ":0] pb;\n    reg signed [" << w_pa - 1 << ":0] pa;\n"
      << "    reg signed [" << w_sum - 1 << ":0] acc_b, acc_a, acc;\n"
      << "    reg signed [" << s.qacc.W() - 1 << ":0] accq;\n\n";
    o << rq.code() << body.str();
    return o.str();
}

// ---------------------------------------------------------------------------
// testbenches
// ---------------------------------------------------------------------------
Vec hdl_test_stimulus(const FxSpec &s, size_t n_taps) {
    const double full = std::ldexp(1.0, s.qi.WI);  // input range -full ... full - LSB
    const size_t L = std::max<size_t>(n_taps, 8);
    Vec x;
    x.push_back(0.5 * full);                        // impulse
    x.insert(x.end(), L + 4, 0.0);
    x.insert(x.end(), 2 * L + 8, 0.5 * full);       // step up
    x.insert(x.end(), 2 * L + 8, -0.5 * full);      // step down
    unsigned long long st = 12345;                  // deterministic pseudo random noise (LCG)
    for (int i = 0; i < 256; ++i) {
        st = st * 6364136223846793005ULL + 1442695040888963407ULL;
        const double u = double(st >> 11) / double(1ULL << 53);
        x.push_back((2 * u - 1) * 0.9 * full);
    }
    x.insert(x.end(), L + 4, 0.0);
    return x;
}

namespace {
struct Vectors {
    std::vector<long long> x, y;
};

Vectors tb_vectors(const Vec &b, const Sos &sos, const FxSpec &s, const Vec &x) {
    const FxResult r = sos.empty() ? fx_filter_fir(b, s, x) : fx_filter_sos(sos, s, x);
    Vectors v;
    for (double xv : r.x_q) v.x.push_back(to_int(xv, s.qi));
    for (double yv : r.y) v.y.push_back(to_int(yv, s.qo));
    return v;
}

std::string int_list(const std::vector<long long> &v, int per_line, const std::string &indent) {
    std::ostringstream o;
    for (size_t i = 0; i < v.size(); ++i) {
        if (i % size_t(per_line) == 0) o << (i ? ",\n" : "") << indent;
        else o << ", ";
        o << v[i];
    }
    return o.str();
}
}  // namespace

std::string export_vhdl_testbench(const Vec &b, const Sos &sos, const FxSpec &s, const Vec &x, const std::string &name_in) {
    if (s.qi.W() > 32 || s.qo.W() > 32)
        throw DesignError("The VHDL testbench needs input and output word lengths <= 32 bits.");
    const std::string name = vhdl_identifier(name_in);
    const Vectors v = tb_vectors(b, sos, s, x);
    std::ostringstream o;
    o << "-- Self-checking testbench for " << name << ", generated by pyfda_cpp\n"
      << "-- The expected output is calculated with the fixpoint model of pyfda_cpp.\n"
      << "-- ghdl -a --std=08 " << name << ".vhd " << name << "_tb.vhd && ghdl -e --std=08 " << name
      << "_tb && ghdl -r --std=08 " << name << "_tb\n\n";
    o << "library ieee;\nuse ieee.std_logic_1164.all;\nuse ieee.numeric_std.all;\n\n";
    o << "entity " << name << "_tb is\nend entity;\n\narchitecture sim of " << name << "_tb is\n";
    o << "    type int_array is array (natural range <>) of integer;\n";
    o << "    constant X_IN : int_array := (\n" << int_list(v.x, 16, "        ") << ");\n";
    o << "    constant Y_REF : int_array := (\n" << int_list(v.y, 16, "        ") << ");\n";
    o << "    signal clk, rst, en : std_logic := '0';\n";
    o << "    signal x : signed(" << s.qi.W() - 1 << " downto 0) := (others => '0');\n";
    o << "    signal y : signed(" << s.qo.W() - 1 << " downto 0);\n";
    o << "begin\n    dut : entity work." << name << " port map (clk => clk, rst => rst, en => en, x => x, y => y);\n\n";
    o << "    clk <= not clk after 5 ns;\n\n";
    o << "    process\n        variable errors : integer := 0;\n    begin\n"
      << "        rst <= '1';\n        wait until rising_edge(clk);\n        rst <= '0';\n"
      << "        for i in X_IN'range loop\n"
      << "            x <= to_signed(X_IN(i), x'length);\n            en <= '1';\n"
      << "            wait until rising_edge(clk);\n            en <= '0';\n            wait for 1 ns;\n"
      << "            if to_integer(y) /= Y_REF(i) then\n                errors := errors + 1;\n"
      << "                report \"sample \" & integer'image(i) & \": y = \" & integer'image(to_integer(y)) &\n"
      << "                       \", expected \" & integer'image(Y_REF(i)) severity error;\n            end if;\n"
      << "            wait until rising_edge(clk);  -- one clock without enable\n        end loop;\n"
      << "        if errors = 0 then\n            report \"PASSED: \" & integer'image(X_IN'length) & \" samples\";\n"
      << "        else\n            report \"FAILED: \" & integer'image(errors) & \" errors\" severity failure;\n"
      << "        end if;\n        std.env.finish;\n    end process;\nend architecture;\n";
    return o.str();
}

std::string export_verilog_testbench(const Vec &b, const Sos &sos, const FxSpec &s, const Vec &x,
                                     const std::string &name_in) {
    const std::string name = vhdl_identifier(name_in);
    const Vectors v = tb_vectors(b, sos, s, x);
    const int wi = s.qi.W(), wo = s.qo.W();
    std::ostringstream o;
    o << "// Self-checking testbench for " << name << ", generated by pyfda_cpp\n"
      << "// The expected output is calculated with the fixpoint model of pyfda_cpp.\n"
      << "// iverilog -o tb " << name << ".v " << name << "_tb.v && vvp tb\n\n";
    o << "`timescale 1ns / 1ps\n\nmodule " << name << "_tb;\n";
    o << "    localparam N = " << v.x.size() << ";\n";
    o << "    reg signed [" << wi - 1 << ":0] X_IN [0:N-1];\n    reg signed [" << wo - 1 << ":0] Y_REF [0:N-1];\n";
    o << "    reg clk = 0, rst = 1, en = 0;\n    reg signed [" << wi - 1 << ":0] x = 0;\n"
      << "    wire signed [" << wo - 1 << ":0] y;\n    integer i, errors;\n\n";
    o << "    " << name << " dut (.clk(clk), .rst(rst), .en(en), .x(x), .y(y));\n\n";
    o << "    always #5 clk = ~clk;\n\n    initial begin\n";
    for (size_t i = 0; i < v.x.size(); ++i)
        o << "        X_IN[" << i << "] = " << vlit(v.x[i], wi) << "; Y_REF[" << i << "] = " << vlit(v.y[i], wo) << ";\n";
    o << "        errors = 0;\n        @(posedge clk);\n        #1 rst = 0;\n"
      << "        for (i = 0; i < N; i = i + 1) begin\n"
      << "            x = X_IN[i];\n            en = 1;\n            @(posedge clk);\n            #1 en = 0;\n"
      << "            if (y !== Y_REF[i]) begin\n                errors = errors + 1;\n"
      << "                $display(\"ERROR sample %0d: y = %0d, expected %0d\", i, y, Y_REF[i]);\n            end\n"
      << "            @(posedge clk);  // one clock without enable\n            #1;\n        end\n"
      << "        if (errors == 0) $display(\"PASSED: %0d samples\", N);\n"
      << "        else $display(\"FAILED: %0d errors\", errors);\n        $finish;\n    end\n\nendmodule\n";
    return o.str();
}

}  // namespace pyfda
