#include "hdl_export.hpp"

#include <algorithm>
#include <cctype>
#include <cmath>
#include <sstream>

namespace pyfda {

std::string export_coe(const Vec &b, const QFormat &qcb, int radix) {
    const Vec bq = quant_coeffs(b, qcb);
    std::ostringstream o;
    o << "; Xilinx COE file exported by pyfda_cpp\n; " << bq.size() << " coefficients, Q" << qcb.WI << "." << qcb.WF
      << " (" << qcb.W() << " bit, two's complement)\n";
    o << "Radix = " << radix << ";\nCoefData =\n";
    for (size_t i = 0; i < bq.size(); ++i) {
        const long long v = to_int(bq[i], qcb);
        o << (radix == 16 ? to_base(v, qcb.W(), 16) : std::to_string(v)) << (i + 1 < bq.size() ? ",\n" : ";\n");
    }
    return o.str();
}

std::string vhdl_identifier(const std::string &name) {
    std::string id;
    for (char c : name) {
        const bool ok = std::isalnum(static_cast<unsigned char>(c)) != 0;
        if (ok) id += char(std::tolower(static_cast<unsigned char>(c)));
        else if (!id.empty() && id.back() != '_') id += '_';
    }
    while (!id.empty() && id.back() == '_') id.pop_back();
    if (id.empty() || !std::isalpha(static_cast<unsigned char>(id[0]))) id = "f_" + id;
    return id;
}

namespace {

int quant_code(Quant q) {
    switch (q) {
    case Quant::Floor: return 0;
    case Quant::Round: return 1;
    case Quant::Fix: return 2;
    case Quant::Ceil: return 3;
    case Quant::None: break;
    }
    throw DesignError("Quantization 'none' can't be implemented in hardware, use floor, round, fix or ceil.");
}

std::string sat(const QFormat &q) { return q.ovfl == Ovfl::Sat ? "true" : "false"; }

int clog2(size_t n) {
    int b = 0;
    while ((size_t(1) << b) < n) ++b;
    return b;
}

void check_width(const QFormat &q, const char *name) {
    if (q.W() < 2 || q.W() > 64) throw DesignError(std::string("The word length of ") + name + " must be 2 ... 64 bits.");
}

// requantization function (VHDL-2008): v has `wf_in` fractional bits, the result has
// `wf_out` fractional bits and `w_out` bits; quantization like numpy floor / round
// (half to even) / trunc / ceil, overflow by saturation or two's complement wrap
const char *REQUANT_FUNC = R"(    -- requantize v with wf_in fractional bits to w_out bits with wf_out fractional bits
    -- q: 0 = floor, 1 = round (half to even), 2 = fix (towards zero), 3 = ceil
    function requant(v : signed; wf_in, wf_out, w_out, q : integer; sat : boolean) return signed is
        constant s : integer := wf_in - wf_out;
        constant wt : integer := maximum(v'length, s + 1) + 2;
        constant we : integer := maximum(wt, v'length + maximum(-s, 0) + 1);
        variable t : signed(wt - 1 downto 0);
        variable e : signed(we - 1 downto 0);
        variable one : signed(we - 1 downto 0);
        variable keep_lsb : std_logic;
    begin
        if s > 0 then
            t := resize(v, wt);
            if q = 1 then
                -- add half an LSB - 1 plus the LSB of the kept part (round half to even)
                if s < v'length then
                    keep_lsb := v(v'low + s);
                else
                    keep_lsb := v(v'high);
                end if;
                t := t + shift_left(to_signed(1, wt), s - 1) - 1;
                if keep_lsb = '1' then
                    t := t + 1;
                end if;
            elsif q = 3 or (q = 2 and v(v'high) = '1') then
                t := t + shift_left(to_signed(1, wt), s) - 1;
            end if;
            e := resize(shift_right(t, s), we);
        else
            e := shift_left(resize(v, we), -s);
        end if;
        if we > w_out then
            if sat then
                one := to_signed(1, we);
                if e > shift_left(one, w_out - 1) - 1 then
                    e := shift_left(one, w_out - 1) - 1;
                elsif e < -shift_left(one, w_out - 1) then
                    e := -shift_left(one, w_out - 1);
                end if;
            end if;
            return e(w_out - 1 downto 0);  -- saturated or two's complement wrap around
        end if;
        return resize(e, w_out);
    end function;
)";

std::string header(const std::string &what, const FxSpec &s, bool iir) {
    std::ostringstream o;
    auto fmt = [](const QFormat &q) {
        std::ostringstream f;
        f << "Q" << q.WI << "." << q.WF << " (" << q.W() << " bit, " << quant_key(q.quant) << ", " << ovfl_key(q.ovfl) << ")";
        return f.str();
    };
    o << "-- " << what << ", generated by pyfda_cpp\n--\n";
    o << "-- input x:        " << fmt(s.qi) << "\n";
    o << "-- coefficients b: " << fmt(s.qcb) << "\n";
    if (iir) o << "-- coefficients a: " << fmt(s.qca) << "\n";
    o << "-- accumulator:    " << fmt(s.qacc) << "\n";
    o << "-- output y:       " << fmt(s.qo) << "\n--\n";
    o << "-- y is registered: the output for the sample x applied with en = '1' is\n"
         "-- available after the next rising clock edge.\n\n";
    o << "library ieee;\nuse ieee.std_logic_1164.all;\nuse ieee.numeric_std.all;\n\n";
    return o.str();
}

std::string entity(const std::string &name, const FxSpec &s) {
    std::ostringstream o;
    o << "entity " << name << " is\n    port (\n        clk : in  std_logic;\n        rst : in  std_logic;\n"
      << "        en  : in  std_logic;\n        x   : in  signed(" << s.qi.W() - 1 << " downto 0);\n"
      << "        y   : out signed(" << s.qo.W() - 1 << " downto 0)\n    );\nend entity;\n\n";
    return o.str();
}

std::string coeff_list(const Vec &c, const QFormat &q, int indent) {
    std::ostringstream o;
    for (size_t i = 0; i < c.size(); ++i) {
        if (i % 4 == 0) o << (i ? ",\n" : "") << std::string(size_t(indent), ' ');
        else o << ", ";
        o << "to_signed(" << to_int(c[i], q) << ", " << q.W() << ")";
    }
    return o.str();
}

}  // namespace

std::string export_vhdl_fir(const Vec &b, const FxSpec &s, const std::string &name_in) {
    for (auto [q, n] : {std::pair{&s.qi, "the input"}, {&s.qcb, "the coefficients"}, {&s.qacc, "the accumulator"},
                        {&s.qo, "the output"}})
        check_width(*q, n);
    quant_code(s.qacc.quant);
    quant_code(s.qo.quant);
    if (b.empty()) throw DesignError("No coefficients.");
    const std::string name = vhdl_identifier(name_in);
    const Vec bq = quant_coeffs(b, s.qcb);
    const size_t L = bq.size();
    const int w_prod = s.qi.W() + s.qcb.W();
    const int w_sum = s.qacc.W() + clog2(L) + 1;
    std::ostringstream o;
    o << header("FIR filter in direct form, " + std::to_string(L) + " taps", s, false) << entity(name, s);
    o << "architecture rtl of " << name << " is\n";
    o << "    constant L : integer := " << L << ";\n";
    o << "    type coeff_t is array (0 to L - 1) of signed(" << s.qcb.W() - 1 << " downto 0);\n";
    o << "    constant B : coeff_t := (\n" << coeff_list(bq, s.qcb, 8) << (L == 1 ? ", others => (others => '0')" : "")
      << ");\n";
    o << "    type taps_t is array (0 to L - 1) of signed(" << s.qi.W() - 1 << " downto 0);\n";
    o << "    signal taps : taps_t := (others => (others => '0'));\n\n" << REQUANT_FUNC << "begin\n";
    o << "    process (clk)\n        variable t : taps_t;\n        variable p : signed(" << w_prod - 1 << " downto 0);\n"
      << "        variable acc : signed(" << w_sum - 1 << " downto 0);\n    begin\n"
      << "        if rising_edge(clk) then\n            if rst = '1' then\n"
      << "                taps <= (others => (others => '0'));\n                y <= (others => '0');\n"
      << "            elsif en = '1' then\n"
      << "                t(0) := x;\n                for i in 1 to L - 1 loop\n                    t(i) := taps(i - 1);\n"
      << "                end loop;\n                acc := (others => '0');\n                for i in 0 to L - 1 loop\n"
      << "                    p := t(i) * B(i);\n"
      << "                    acc := acc + resize(requant(p, " << s.qi.WF + s.qcb.WF << ", " << s.qacc.WF << ", "
      << s.qacc.W() << ", " << quant_code(s.qacc.quant) << ", " << sat(s.qacc) << "), acc'length);\n"
      << "                end loop;\n"
      << "                y <= requant(requant(acc, " << s.qacc.WF << ", " << s.qacc.WF << ", " << s.qacc.W() << ", 0, "
      << sat(s.qacc) << "), " << s.qacc.WF << ", " << s.qo.WF << ", " << s.qo.W() << ", " << quant_code(s.qo.quant)
      << ", " << sat(s.qo) << ");\n"
      << "                taps <= t;\n            end if;\n        end if;\n    end process;\nend architecture;\n";
    return o.str();
}

std::string export_vhdl_sos(const Sos &sos, const FxSpec &s, const std::string &name_in) {
    for (auto [q, n] : {std::pair{&s.qi, "the input"}, {&s.qcb, "the b coefficients"}, {&s.qca, "the a coefficients"},
                        {&s.qacc, "the accumulator"}, {&s.qo, "the output"}})
        check_width(*q, n);
    quant_code(s.qacc.quant);
    quant_code(s.qo.quant);
    if (sos.empty()) throw DesignError("No second-order sections.");
    const std::string name = vhdl_identifier(name_in);
    Vec b, a;
    for (const auto &sec : sos) {
        if (sec[3] != 1.0) throw DesignError("Second-order sections must be normalized to a0 = 1.");
        b.insert(b.end(), {sec[0], sec[1], sec[2]});
        a.insert(a.end(), {sec[4], sec[5]});
    }
    const Vec bq = quant_coeffs(b, s.qcb), aq = quant_coeffs(a, s.qca);
    const size_t n = sos.size();
    // the section inputs are the filter input (section 0) or the outputs of the previous section,
    // registers are kept in a common format with WF_s fractional and W_s bits
    const int wf_s = std::max(s.qi.WF, s.qo.WF);
    const int wi_s = std::max(s.qi.WI, s.qo.WI);
    const int w_s = wi_s + wf_s + 1;
    const int w_sum = s.qacc.W() + 4;
    std::ostringstream o;
    o << header("IIR filter, cascade of " + std::to_string(n) + " second-order sections in direct form 1", s, true)
      << entity(name, s);
    o << "architecture rtl of " << name << " is\n";
    o << "    constant NS : integer := " << n << ";\n";
    o << "    type b_t is array (0 to 3 * NS - 1) of signed(" << s.qcb.W() - 1 << " downto 0);\n";
    o << "    type a_t is array (0 to 2 * NS - 1) of signed(" << s.qca.W() - 1 << " downto 0);\n";
    o << "    -- b0, b1, b2 of every section\n    constant B : b_t := (\n" << coeff_list(bq, s.qcb, 8) << ");\n";
    o << "    -- a1, a2 of every section (a0 = 1)\n    constant A : a_t := (\n" << coeff_list(aq, s.qca, 8) << ");\n";
    o << "    -- section inputs and outputs with " << wf_s << " fractional bits\n";
    o << "    type reg_t is array (0 to NS - 1) of signed(" << w_s - 1 << " downto 0);\n";
    o << "    signal x1, x2, y1, y2 : reg_t := (others => (others => '0'));\n\n" << REQUANT_FUNC << "begin\n";
    o << "    process (clk)\n        variable xs, ys : signed(" << w_s - 1 << " downto 0);\n"
      << "        variable yo : signed(" << s.qo.W() - 1 << " downto 0);\n"
      << "        variable acc_b, acc_a : signed(" << w_sum - 1 << " downto 0);\n"
      << "        variable acc : signed(" << s.qacc.W() - 1 << " downto 0);\n    begin\n"
      << "        if rising_edge(clk) then\n            if rst = '1' then\n"
      << "                x1 <= (others => (others => '0'));\n                x2 <= (others => (others => '0'));\n"
      << "                y1 <= (others => (others => '0'));\n                y2 <= (others => (others => '0'));\n"
      << "                y <= (others => '0');\n            elsif en = '1' then\n"
      << "                xs := shift_left(resize(x, xs'length), " << wf_s - s.qi.WF << ");\n"
      << "                for k in 0 to NS - 1 loop\n";
    auto prod_b = [&](const std::string &c, const std::string &v) {
        return "resize(requant(" + v + " * " + c + ", " + std::to_string(wf_s + s.qcb.WF) + ", " +
               std::to_string(s.qacc.WF) + ", " + std::to_string(s.qacc.W()) + ", " +
               std::to_string(quant_code(s.qacc.quant)) + ", " + sat(s.qacc) + "), acc_b'length)";
    };
    auto prod_a = [&](const std::string &c, const std::string &v) {
        return "resize(requant(" + v + " * " + c + ", " + std::to_string(wf_s + s.qca.WF) + ", " +
               std::to_string(s.qacc.WF) + ", " + std::to_string(s.qacc.W()) + ", " +
               std::to_string(quant_code(s.qacc.quant)) + ", " + sat(s.qacc) + "), acc_a'length)";
    };
    o << "                    acc_b := " << prod_b("B(3 * k)", "xs") << "\n                           + "
      << prod_b("B(3 * k + 1)", "x1(k)") << "\n                           + " << prod_b("B(3 * k + 2)", "x2(k)")
      << ";\n";
    o << "                    acc_a := " << prod_a("A(2 * k)", "y1(k)") << "\n                           + "
      << prod_a("A(2 * k + 1)", "y2(k)") << ";\n";
    o << "                    acc := requant(acc_b - acc_a, " << s.qacc.WF << ", " << s.qacc.WF << ", " << s.qacc.W()
      << ", 0, " << sat(s.qacc) << ");\n";
    o << "                    yo := requant(acc, " << s.qacc.WF << ", " << s.qo.WF << ", " << s.qo.W() << ", "
      << quant_code(s.qo.quant) << ", " << sat(s.qo) << ");\n";
    o << "                    ys := shift_left(resize(yo, ys'length), " << wf_s - s.qo.WF << ");\n";
    o << "                    x2(k) <= x1(k);\n                    x1(k) <= xs;\n"
      << "                    y2(k) <= y1(k);\n                    y1(k) <= ys;\n"
      << "                    xs := ys;  -- input of the next section\n                end loop;\n"
      << "                y <= yo;\n            end if;\n        end if;\n    end process;\nend architecture;\n";
    return o.str();
}

}  // namespace pyfda
