#!/usr/bin/env python3
"""
Simulate the VHDL generated by pyfda_cpp with GHDL and the Verilog with Icarus Verilog
and compare the output bit by bit with the fixpoint model of the C++ core
(fx_filter_fir / fx_filter_sos). Also runs the generated self-checking testbenches.

Usage: python tests/verify_vhdl.py build/pyfda_cli
Needs `ghdl` and `iverilog` in the PATH (e.g. `apt install ghdl iverilog`).
"""
import json
import os
import shutil
import subprocess
import sys
import tempfile

import numpy as np
import scipy.signal as sig

cli = sys.argv[1] if len(sys.argv) > 1 else "build/pyfda_cli"
if not shutil.which("ghdl"):
    sys.exit("ghdl not found")
if not shutil.which("iverilog"):
    sys.exit("iverilog not found")
proc = subprocess.Popen([cli], stdin=subprocess.PIPE, stdout=subprocess.PIPE, text=True, encoding="utf-8")


def call(line):
    proc.stdin.write(line + "\n")
    proc.stdin.flush()
    r = json.loads(proc.stdout.readline())
    if 'error' in r:
        raise RuntimeError(r['error'])
    return r


L = lambda v: ",".join(repr(float(a)) for a in np.ravel(v))
fq = lambda t: ",".join(map(str, t))

TB = """library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use std.textio.all;

entity tb is
end entity;

architecture sim of tb is
    type int_array is array (natural range <>) of integer;
    constant X_IN : int_array := ({x});
    signal clk, rst, en : std_logic := '0';
    signal x : signed({wi} - 1 downto 0) := (others => '0');
    signal y : signed({wo} - 1 downto 0);
begin
    dut : entity work.{name} port map (clk => clk, rst => rst, en => en, x => x, y => y);
    process
        file f : text open write_mode is "y.txt";
        variable l : line;
    begin
        rst <= '1';
        wait for 5 ns; clk <= '1'; wait for 5 ns; clk <= '0';
        rst <= '0';
        for i in X_IN'range loop
            x <= to_signed(X_IN(i), {wi});
            en <= '1';
            wait for 5 ns; clk <= '1'; wait for 1 ns;
            write(l, to_integer(y));
            writeline(f, l);
            wait for 4 ns; clk <= '0';
            -- a clock without enable must not change the state
            en <= '0';
            wait for 5 ns; clk <= '1'; wait for 5 ns; clk <= '0';
        end loop;
        wait;
    end process;
end architecture;
"""

VTB = """`timescale 1ns / 1ps
module tb;
    reg clk = 0, rst = 1, en = 0;
    reg signed [{wi} - 1:0] x = 0;
    wire signed [{wo} - 1:0] y;
    integer i, f;
    reg signed [31:0] X_IN [0:{n} - 1];
    {name} dut (.clk(clk), .rst(rst), .en(en), .x(x), .y(y));
    initial begin
{init}
        f = $fopen("y.txt", "w");
        #5 clk = 1; #5 clk = 0;
        rst = 0;
        for (i = 0; i < {n}; i = i + 1) begin
            x = X_IN[i];
            en = 1;
            #5 clk = 1; #1;
            $fdisplay(f, "%0d", y);
            #4 clk = 0;
            en = 0;
            #5 clk = 1; #5 clk = 0;
        end
        $fclose(f);
        $finish;
    end
endmodule
"""


def run(cmds, cwd):
    out = ""
    for cmd in cmds:
        out += subprocess.run(cmd, cwd=cwd, check=True, capture_output=True, text=True).stdout
    return out


n_pass = n_fail = 0
rng = np.random.default_rng(3)
x = np.clip(rng.normal(0, 0.35, 300), -0.99, 0.99)
x[:5] = [0.99, -0.99, 0.99, -0.99, 0.99]  # provoke overflows
fir = sig.firwin(25, 0.2) * np.linspace(0.9, 1.1, 25)
sos = sig.ellip(6, 0.5, 50, 0.15, output='sos')
sos_hot = sos.copy()
sos_hot[0, :3] *= 1.9  # gain > 1: overflows
cases = [
    ("fir", fir, dict(qi=(0, 11, 'round', 'sat'), qcb=(0, 13, 'round', 'sat'), qacc=(2, 24, 'floor', 'wrap'),
                      qo=(0, 11, 'round', 'sat'))),
    ("fir", fir, dict(qi=(0, 7, 'round', 'sat'), qcb=(0, 9, 'floor', 'wrap'), qacc=(1, 10, 'round', 'sat'),
                      qo=(0, 5, 'fix', 'wrap'))),
    ("fir", fir * 3, dict(qi=(0, 15, 'round', 'sat'), qcb=(1, 14, 'round', 'sat'), qacc=(0, 20, 'ceil', 'wrap'),
                          qo=(1, 8, 'round', 'sat'))),
    ("sos", sos, dict(qi=(0, 15, 'round', 'sat'), qcb=(1, 16, 'round', 'sat'), qca=(1, 16, 'round', 'sat'),
                      qacc=(4, 32, 'floor', 'wrap'), qo=(1, 15, 'round', 'sat'))),
    ("sos", sos, dict(qi=(0, 9, 'round', 'sat'), qcb=(1, 10, 'floor', 'sat'), qca=(1, 12, 'round', 'sat'),
                      qacc=(3, 14, 'round', 'sat'), qo=(2, 10, 'fix', 'wrap'))),
    ("sos", sos, dict(qi=(1, 20, 'round', 'sat'), qcb=(1, 24, 'round', 'sat'), qca=(1, 24, 'round', 'sat'),
                      qacc=(5, 40, 'ceil', 'wrap'), qo=(0, 20, 'round', 'sat'))),
    # overflows in the accumulator and the output (saturation and wrap around)
    ("fir", fir * 4, dict(qi=(1, 10, 'round', 'sat'), qcb=(1, 12, 'round', 'sat'), qacc=(0, 18, 'floor', 'wrap'),
                          qo=(0, 9, 'round', 'sat')), 2.5),
    ("fir", fir * 4, dict(qi=(1, 10, 'round', 'sat'), qcb=(1, 12, 'round', 'sat'), qacc=(1, 18, 'floor', 'sat'),
                          qo=(0, 9, 'round', 'wrap')), 2.5),
    ("sos", sos_hot, dict(qi=(1, 12, 'round', 'sat'), qcb=(1, 14, 'round', 'sat'),
                      qca=(1, 14, 'round', 'sat'), qacc=(1, 20, 'floor', 'sat'), qo=(0, 12, 'round', 'sat')), 2.5),
    ("sos", sos_hot, dict(qi=(1, 12, 'round', 'sat'), qcb=(1, 14, 'round', 'sat'), qca=(1, 14, 'round', 'sat'),
                      qacc=(1, 20, 'floor', 'wrap'), qo=(0, 12, 'round', 'wrap')), 2.5),
]
def report(ok, what, detail=""):
    global n_pass, n_fail
    if ok:
        n_pass += 1
        print(f"ok   {what}")
    else:
        n_fail += 1
        print(f"FAIL {what}: {detail}")


def first_diff(y_hdl, y_ref):
    if len(y_hdl) != len(y_ref):
        return f"length {len(y_hdl)} != {len(y_ref)}"
    return f"first difference at {next(k for k, (a, b) in enumerate(zip(y_hdl, y_ref)) if a != b)}"


for i, case in enumerate(cases):
    kind, c, q = case[:3]
    amp = case[3] if len(case) > 3 else 1.0
    keys = " ".join(f"{k}={fq(v)}" for k, v in q.items())
    model = call(f"fx{kind} {L(c)} {L(x * amp)} {keys}")
    vhdl = call(f"vhdl {kind} {L(c)} {keys}")['text']
    verilog = call(f"verilog {kind} {L(c)} {keys}")['text']
    name = "fir_filter" if kind == "fir" else "iir_filter"
    WFi, WFo = q['qi'][1], q['qo'][1]
    wi, wo = sum(q['qi'][:2]) + 1, sum(q['qo'][:2]) + 1
    x_int = [int(round(v * 2**WFi)) for v in model['x_q']]
    y_ref = [int(round(v * 2**WFo)) for v in model['y']]
    info = f"{kind} {keys} (overflows i/acc/o: {model['ov'][:3]})"
    # VHDL with GHDL
    with tempfile.TemporaryDirectory() as tmp:
        open(os.path.join(tmp, "dut.vhd"), "w").write(vhdl)
        open(os.path.join(tmp, "tb.vhd"), "w").write(TB.format(x=", ".join(map(str, x_int)), wi=wi, wo=wo, name=name))
        try:
            run([["ghdl", "-a", "--std=08", "dut.vhd", "tb.vhd"], ["ghdl", "-e", "--std=08", "tb"],
                 ["ghdl", "-r", "--std=08", "tb", "--stop-time=100us"]], tmp)
            y_hdl = [int(l) for l in open(os.path.join(tmp, "y.txt")).read().split()]
            report(y_hdl == y_ref, "vhdl " + info, "" if y_hdl == y_ref else first_diff(y_hdl, y_ref))
        except subprocess.CalledProcessError as e:
            report(False, "vhdl " + info, (e.stderr or e.stdout)[-2000:])
    # Verilog with Icarus Verilog
    with tempfile.TemporaryDirectory() as tmp:
        open(os.path.join(tmp, "dut.v"), "w").write(verilog)
        init = "\n".join(f"        X_IN[{k}] = {v};" for k, v in enumerate(x_int))
        open(os.path.join(tmp, "tb.v"), "w").write(VTB.format(wi=wi, wo=wo, n=len(x_int), name=name, init=init))
        try:
            run([["iverilog", "-g2005", "-Wall", "-o", "sim", "dut.v", "tb.v"], ["vvp", "-n", "sim"]], tmp)
            y_hdl = [int(l) for l in open(os.path.join(tmp, "y.txt")).read().split()]
            report(y_hdl == y_ref, "verilog " + info, "" if y_hdl == y_ref else first_diff(y_hdl, y_ref))
        except subprocess.CalledProcessError as e:
            report(False, "verilog " + info, (e.stderr or e.stdout)[-2000:])
    if os.environ.get("KEEP_VHDL"):
        open(f"case{i}.vhd", "w").write(vhdl)
        open(f"case{i}.v", "w").write(verilog)
    # generated self-checking testbenches with the default test signal (W <= 32 for VHDL)
    if i % 3 == 0 or 'wrap' in q['qo']:
        for lang in ("vhdl", "verilog"):
            tb = call(f"tb {lang} {kind} {L(c)} - {keys}")['text']
            with tempfile.TemporaryDirectory() as tmp:
                try:
                    if lang == "vhdl":
                        open(os.path.join(tmp, f"{name}.vhd"), "w").write(vhdl)
                        open(os.path.join(tmp, f"{name}_tb.vhd"), "w").write(tb)
                        out = run([["ghdl", "-a", "--std=08", f"{name}.vhd", f"{name}_tb.vhd"],
                                   ["ghdl", "-e", "--std=08", f"{name}_tb"],
                                   ["ghdl", "-r", "--std=08", f"{name}_tb"]], tmp)
                    else:
                        open(os.path.join(tmp, f"{name}.v"), "w").write(verilog)
                        open(os.path.join(tmp, f"{name}_tb.v"), "w").write(tb)
                        out = run([["iverilog", "-g2005", "-o", "sim", f"{name}.v", f"{name}_tb.v"], ["vvp", "-n", "sim"]], tmp)
                    report("PASSED" in out and "FAIL" not in out and "ERROR" not in out, f"{lang} testbench {kind} {keys}",
                           out[-1000:])
                except subprocess.CalledProcessError as e:
                    report(False, f"{lang} testbench {kind} {keys}", (e.stderr + e.stdout)[-2000:])

proc.stdin.close()
proc.wait()
print(f"{n_pass} HDL simulations bit exact / testbenches passed, {n_fail} failed")
sys.exit(1 if n_fail else 0)
