#!/usr/bin/env python3
"""
Simulate the VHDL generated by pyfda_cpp with GHDL and compare the output bit by bit
with the fixpoint model of the C++ core (fx_filter_fir / fx_filter_sos).

Usage: python tests/verify_vhdl.py build/pyfda_cli
Needs `ghdl` in the PATH (e.g. `apt install ghdl`).
"""
import json
import os
import shutil
import subprocess
import sys
import tempfile

import numpy as np
import scipy.signal as sig

cli = sys.argv[1] if len(sys.argv) > 1 else "build/pyfda_cli"
if not shutil.which("ghdl"):
    sys.exit("ghdl not found")
proc = subprocess.Popen([cli], stdin=subprocess.PIPE, stdout=subprocess.PIPE, text=True, encoding="utf-8")


def call(line):
    proc.stdin.write(line + "\n")
    proc.stdin.flush()
    r = json.loads(proc.stdout.readline())
    if 'error' in r:
        raise RuntimeError(r['error'])
    return r


L = lambda v: ",".join(repr(float(a)) for a in np.ravel(v))
fq = lambda t: ",".join(map(str, t))

TB = """library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use std.textio.all;

entity tb is
end entity;

architecture sim of tb is
    type int_array is array (natural range <>) of integer;
    constant X_IN : int_array := ({x});
    signal clk, rst, en : std_logic := '0';
    signal x : signed({wi} - 1 downto 0) := (others => '0');
    signal y : signed({wo} - 1 downto 0);
begin
    dut : entity work.{name} port map (clk => clk, rst => rst, en => en, x => x, y => y);
    process
        file f : text open write_mode is "y.txt";
        variable l : line;
    begin
        rst <= '1';
        wait for 5 ns; clk <= '1'; wait for 5 ns; clk <= '0';
        rst <= '0';
        for i in X_IN'range loop
            x <= to_signed(X_IN(i), {wi});
            en <= '1';
            wait for 5 ns; clk <= '1'; wait for 1 ns;
            write(l, to_integer(y));
            writeline(f, l);
            wait for 4 ns; clk <= '0';
            -- a clock without enable must not change the state
            en <= '0';
            wait for 5 ns; clk <= '1'; wait for 5 ns; clk <= '0';
        end loop;
        wait;
    end process;
end architecture;
"""

n_pass = n_fail = 0
rng = np.random.default_rng(3)
x = np.clip(rng.normal(0, 0.35, 300), -0.99, 0.99)
x[:5] = [0.99, -0.99, 0.99, -0.99, 0.99]  # provoke overflows
fir = sig.firwin(25, 0.2) * np.linspace(0.9, 1.1, 25)
sos = sig.ellip(6, 0.5, 50, 0.15, output='sos')
sos_hot = sos.copy()
sos_hot[0, :3] *= 1.9  # gain > 1: overflows
cases = [
    ("fir", fir, dict(qi=(0, 11, 'round', 'sat'), qcb=(0, 13, 'round', 'sat'), qacc=(2, 24, 'floor', 'wrap'),
                      qo=(0, 11, 'round', 'sat'))),
    ("fir", fir, dict(qi=(0, 7, 'round', 'sat'), qcb=(0, 9, 'floor', 'wrap'), qacc=(1, 10, 'round', 'sat'),
                      qo=(0, 5, 'fix', 'wrap'))),
    ("fir", fir * 3, dict(qi=(0, 15, 'round', 'sat'), qcb=(1, 14, 'round', 'sat'), qacc=(0, 20, 'ceil', 'wrap'),
                          qo=(1, 8, 'round', 'sat'))),
    ("sos", sos, dict(qi=(0, 15, 'round', 'sat'), qcb=(1, 16, 'round', 'sat'), qca=(1, 16, 'round', 'sat'),
                      qacc=(4, 32, 'floor', 'wrap'), qo=(1, 15, 'round', 'sat'))),
    ("sos", sos, dict(qi=(0, 9, 'round', 'sat'), qcb=(1, 10, 'floor', 'sat'), qca=(1, 12, 'round', 'sat'),
                      qacc=(3, 14, 'round', 'sat'), qo=(2, 10, 'fix', 'wrap'))),
    ("sos", sos, dict(qi=(1, 20, 'round', 'sat'), qcb=(1, 24, 'round', 'sat'), qca=(1, 24, 'round', 'sat'),
                      qacc=(5, 40, 'ceil', 'wrap'), qo=(0, 20, 'round', 'sat'))),
    # overflows in the accumulator and the output (saturation and wrap around)
    ("fir", fir * 4, dict(qi=(1, 10, 'round', 'sat'), qcb=(1, 12, 'round', 'sat'), qacc=(0, 18, 'floor', 'wrap'),
                          qo=(0, 9, 'round', 'sat')), 2.5),
    ("fir", fir * 4, dict(qi=(1, 10, 'round', 'sat'), qcb=(1, 12, 'round', 'sat'), qacc=(1, 18, 'floor', 'sat'),
                          qo=(0, 9, 'round', 'wrap')), 2.5),
    ("sos", sos_hot, dict(qi=(1, 12, 'round', 'sat'), qcb=(1, 14, 'round', 'sat'),
                      qca=(1, 14, 'round', 'sat'), qacc=(1, 20, 'floor', 'sat'), qo=(0, 12, 'round', 'sat')), 2.5),
    ("sos", sos_hot, dict(qi=(1, 12, 'round', 'sat'), qcb=(1, 14, 'round', 'sat'), qca=(1, 14, 'round', 'sat'),
                      qacc=(1, 20, 'floor', 'wrap'), qo=(0, 12, 'round', 'wrap')), 2.5),
]
for i, case in enumerate(cases):
    kind, c, q = case[:3]
    amp = case[3] if len(case) > 3 else 1.0
    keys = " ".join(f"{k}={fq(v)}" for k, v in q.items())
    model = call(f"fx{kind} {L(c)} {L(x * amp)} {keys}")
    vhdl = call(f"vhdl {kind} {L(c)} {keys}")['text']
    name = "fir_filter" if kind == "fir" else "iir_filter"
    WFi, WFo = q['qi'][1], q['qo'][1]
    x_int = [int(round(v * 2**WFi)) for v in model['x_q']]
    y_ref = [int(round(v * 2**WFo)) for v in model['y']]
    with tempfile.TemporaryDirectory() as tmp:
        with open(os.path.join(tmp, "dut.vhd"), "w") as f:
            f.write(vhdl)
        with open(os.path.join(tmp, "tb.vhd"), "w") as f:
            f.write(TB.format(x=", ".join(map(str, x_int)), wi=sum(q['qi'][:2]) + 1, wo=sum(q['qo'][:2]) + 1,
                              name=name))
        try:
            for cmd in (["ghdl", "-a", "--std=08", "dut.vhd", "tb.vhd"], ["ghdl", "-e", "--std=08", "tb"],
                        ["ghdl", "-r", "--std=08", "tb", "--stop-time=100us"]):
                subprocess.run(cmd, cwd=tmp, check=True, capture_output=True, text=True)
            with open(os.path.join(tmp, "y.txt")) as f:
                y_hdl = [int(l) for l in f.read().split()]
            ok = y_hdl == y_ref
            detail = "" if ok else f"first difference at {next(k for k, (a, b) in enumerate(zip(y_hdl, y_ref)) if a != b) if len(y_hdl) == len(y_ref) else 'length'}"
        except subprocess.CalledProcessError as e:
            ok, detail = False, (e.stderr or e.stdout)[-2000:]
    if ok:
        n_pass += 1
        print(f"ok   vhdl {kind} {keys} (overflows i/acc/o: {model['ov'][:3]})")
    else:
        n_fail += 1
        print(f"FAIL vhdl {kind} {keys}: {detail}")
        if os.environ.get("KEEP_VHDL"):
            open(f"fail{i}.vhd", "w").write(vhdl)

proc.stdin.close()
proc.wait()
print(f"{n_pass} VHDL simulations bit exact, {n_fail} failed")
sys.exit(1 if n_fail else 0)
